name: push-develop
on: [push]
jobs:
  precheck:
    runs-on: ubuntu-latest
    outputs:
      files_changed: ${{ steps.file_changes.outputs.diff }}
    steps:
      - uses: actions/checkout@v2
      - id: file_changes
        run: |
          diff=$(git diff -- helloworld/src/main/scala/example/hello.scala)
          echo $diff
          echo "::set-output name=diff::$diff"
