name: push-develop
on: [push]
jobs:
  precheck:
    runs-on: ubuntu-latest
    outputs:
      files_changed: ${{ steps.file_changes.outputs.diff }}
    steps:
      - uses: actions/checkout@v3
      - id: file_changes
        run: |
          git diff -- project/Dependencies.scala --exit-code
          echo "::set-output name=diff::$?"

